# Generated by Django 4.0.5 on 2022-06-07 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='Producto')),
                ('marca', models.CharField(max_length=20, verbose_name='Marca')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=40, verbose_name='Descripcion')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MascoApp.categoria')),
            ],
        ),
    ]
