# Generated by Django 4.0.5 on 2022-06-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
    ]
