# Generated by Django 4.0.5 on 2022-06-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MascoApp', '0002_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('run', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Run')),
                ('genero', models.CharField(max_length=15, verbose_name='Genero')),
                ('nombrecliente', models.CharField(max_length=40, verbose_name='NombreCliente')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('estado', models.CharField(max_length=12, verbose_name='Estado')),
                ('ocupacion', models.CharField(max_length=30, verbose_name='Ocupacion')),
            ],
        ),
    ]
